#!/bin/sh
set -e

CONFIG=/etc/tor/torrc

printenv | grep '^TOR_' | sed -E 's/TOR_([^=]*)=(.*)/\1 \2/' > $CONFIG
cat << EOF >> $CONFIG
SOCKSPort 127.0.0.1:9050
DataDirectory /var/lib/tor
EOF

chown -Rh nobody:nogroup /var/lib/tor

exec gosu nobody:nogroup tor -f $CONFIG
