#!/bin/sh
set -e

CONFIG=/etc/3proxy/3proxy.cfg

touch $CONFIG
chmod 0644 $CONFIG

cat << EOF > $CONFIG
log
fakeresolve
timeouts 30 30 60 60 180 1800 60 120
internal 0.0.0.0
users "${PROXY_USER}:CL:${PROXY_PASSWORD}"
auth strong
allow ${PROXY_USER}
parent 1000 socks5+ 127.0.0.1 9050
socks -p1080
EOF

exec s6-setuidgid nobody 3proxy $CONFIG
