#!/bin/sh
set -e

CONFIG=/etc/3proxy/3proxy.cfg

touch $CONFIG
chmod 0644 $CONFIG

cat << EOF > $CONFIG
log
logformat "L%o %d %H:%M:%S.%. [%N.%p] %E (%U %C:%c) %R:%r %O/%I/%h: %T"

timeouts 30 30 60 60 180 1800 60 120
internal 0.0.0.0

nserver 127.0.0.1:5353

users "${PROXY_USER}:CL:${PROXY_PASSWORD}"
auth strong
allow * * 127.0.0.2
parent 1000 socks5+ 127.0.0.1 9050
allow *
parent 1000 socks5 127.0.0.1 9050
socks -p1080
EOF

exec s6-setuidgid nobody 3proxy $CONFIG
